# Generated by Django 3.1.5 on 2021-02-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Htf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gene_id', models.CharField(max_length=30)),
                ('gene_symbol', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30)),
                ('cell_location', models.CharField(max_length=30)),
                ('gene_regulation', models.CharField(max_length=30)),
                ('drugs', models.ManyToManyField(to='data.Drug')),
            ],
        ),
    ]
